<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="hp" ignored="0" name="Retry Mutiple Failed Test Cases" tests="5" failures="1" timestamp="08 May 2019 11:40:43 GMT" time="0.079" errors="0">
  <testcase name="test" time="0.012" classname="retrypackage.RetryTests"/>
  <testcase name="test1" time="0.004" classname="retrypackage.RetryTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="retrypackage.RetryTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="retrypackage.RetryTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="retrypackage.RetryTests">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at retrypackage.RetryTests.test1(RetryTests.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Retry Mutiple Failed Test Cases -->
